extends: default
rules:
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy: disable# Updated 20251109_123839
# Updated Sun Nov  9 12:49:15 CET 2025
# Updated Sun Nov  9 12:52:45 CET 2025
# Updated Sun Nov  9 12:55:57 CET 2025
